### ISSUE TITLE
Does not support multiple database definitions

### ISSUE THREAD

**Issue by isotopp** [datacentred/datacentred-ldap#13]
OpenLDAP Servers can host multiple database definitions, each starting with "database". By default, the server should have the monitor, config and the payload database (the latter using bdb or hdb as a backend).

The server can have any number of payload databases, each with their own bdb/hdb or other backend.

The template and the class infrastructure do not carry this.

**Comment by seanhandley** [comment]
Sorry @isotopp - we don't get much time to maintain this module (though pull requests are welcome if you find/fix a bug in the Puppet code itself!)

I'm closing this issue - feel free to re-open if you have more to add.
