### ISSUE TITLE
ACL support is missing

### ISSUE THREAD

**Issue by isotopp** [datacentred/datacentred-ldap#15]
A useful LDAP database declaration in slapd.conf will need a database specific ACL declaration.

A first approximation for support would accept an array of ACL clauses which are simply added as a stanza of lines to the database declaration. This should be relatively easy to add.

A more complete implementation would have some kind of DSL or type notation that would allow a more user friendly declaration of ACL rules. It can be argued that this is useless, as this adds no value to the project and even substracts value.

Adding value would mean that the thing would become more portable, or a whole lot easier to understand than native slapd ACL syntax. Substracting value is when not all native functionality is accessible through using the DSL/type notation, because that added abstraction is less expressive than the native ACL notation.

**Comment by bilco105** [comment]
ACL support was added back in #39, so closing this.
