### ISSUE TITLE
Unable to login to OpenLDAP on CentOS 7

### ISSUE THREAD

**Issue by fatmcgav** [datacentred/datacentred-ldap#32]
Hi there, 

I've been using this module with great success on CentOS 6 hosts with OpenLDAP 2.4.23.
However upon trying on a CentOS 7 host with OpenLDAP 2.4.39, I get the following error:

```puppet
Info: Applying configuration version '1413552149'
Debug: Prefetching gem resources for package
Debug: Executing '/bin/gem list --local'
Debug: Prefetching yum resources for package
Debug: Executing '/bin/rpm --version'
Debug: Executing '/bin/rpm -qa --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Debug: Executing '/bin/systemctl is-active slapd'
Debug: Executing '/bin/systemctl is-enabled slapd'
Debug: Connecting to LDAP server ldaps://localhost:389
Debug: LDAP Search: {:base=>"dc=dt0388,dc=local", :attributes=>["dc", "objectClass"]}
Error: /Stage[main]/Main/Ldap_entry[dc=dt0388,dc=local]: Could not evaluate: LDAP Error 49: Invalid Credentials. Check server log for more info.
```

This is using the simple manifest here: https://gist.github.com/fatmcgav/05c5f011c10f88d17f05

I get the same error if I try and access OpenLDAP using other tools, such as Apache Directory Studio, so it looks like it's a configuration issue of some sort... 

However I've been unable to spot anything obvious. Maybe there's some behavior change between OpenLDAP 2.4.23 and 2.4.39???

Any pointers?

Cheers
Gavin

**Comment by bilco105** [comment]
Closing this, as there's already a PR for OLC support in the form of #16
