### ISSUE TITLE
Initial Password for ldap_entry

### ISSUE THREAD

**Issue by graeson** [datacentred/datacentred-ldap#65]
Hi! I would like to use datacentred-ldap to provision user accounts within our LDAP directory. Our users are created with an initial password which is subsequently changed by the user. On the next puppet run, however, puppet resets the user's password back to the initial password specified in the ldap_entry. Are there any workaround you can suggest?

**Comment by spjmurray** [comment]
The easy way is just to remove the resource definition and have the account unmanaged post provisioning. However, as I'm sure you are eager to have some form of auditing and version control I can extend the type to optionally only manage the attributes on initial creation for this use case. I'll discuss it with the lads and try get a release on the forge today

**Comment by spjmurray** [comment]
Note to self: 'mutable' attribute defining list of attributes which must exist, but not necessarily match

**Comment by bilco105** [comment]
Hi @graeson, 

Take a look at #66 - this takes care of it for you.

Will release a new version to the forge shortly.
