### ISSUE TITLE
Error: Could not find a suitable provider for ldap_entry

### ISSUE THREAD

**Issue by pedroresende** [datacentred/datacentred-ldap#70]
I have the following configuration
```
class { 'ldap::server':
  suffix  => 'dc=piu,dc=de',
  rootdn  => 'cn=admin,dc=piu,dc=de',
  rootpw  => '{MD5}FLasFExRTZnaVKq2ALMPAA==',
}

class { 'ldap::client':
  uri  => 'ldap://127.0.0.1',
  base => 'dc=piu,dc=de',
}

ldap_entry { 'cn=groups,dc=piu,dc=de':
  ensure      => present,
  base        => 'dc=piu,dc=de',
  host        => 'ldap://127.0.0.1',
  username    => 'cn=test,cn=groups,dc=piu,dc=de',
  password    => '{MD5}FLasFExRTZnaVKq2ALMPAA==',
}
```

**Comment by dc-mattj** [comment]
That's not a configuration problem, your puppet master doesn't know about the provider. Is the module installed correctly ?

**Comment by pedroresende** [comment]
@dc-mattj I'm trying to use it directly in a puphpet vagrant generated. I've downloaded the release and exported it to puppet/modules folder.
Apparently the part of the server and client it's working, the only problem is when I try to add a new ldap_entry.
Is there a way to call the ldap_entry from inside the class declaration ?

**Comment by dc-mattj** [comment]
Types and providers should just work in that configuration. Do other custom providers and types work ?

**Comment by pedroresende** [comment]
The one that are generated by puphpnet work correctly

**Comment by dc-mattj** [comment]
I've never used puphpnet, so no idea how that's supposed to work I'm afraid.

**Comment by JWGmeligMeyling** [comment]
Same issue here, not using puphpnet, just puppet + librarian + vagrant.

**Comment by spjmurray** [comment]
I take it you are all running puppet 4?  This appears to be the secret sauce that's not been mentioned.  I shall re-architect and get a fix out asap.

**Comment by JWGmeligMeyling** [comment]
I am on Puppet 3.x.x as I couldn't get 4.x.x to work with Vagrant:https://github.com/mitchellh/vagrant/issues/5615 . Still have to look in that issue. Is this package not supported on puopet 3?

**Comment by spjmurray** [comment]
Interesting, I've just run the above manifest on 3.8.5 fine, but it fails on 4.3.2.  Either way it's flaking out due to the provider being confined to systems with the net_ldap feature.  I'll fix that up/amend the documentation and add beaker acceptance testing for puppet 3.x and 4.x on centos 7 and ubuntu 14.04.

**Comment by spjmurray** [comment]
Notes
* Puppet 4 uses its own collection of gems (ignores /usr/lib/ruby), which doesn't include net/ldap.  Manually copying it into '/opt/puppetlabs/puppet/lib/ruby/2.1.0/net' works
* Ubuntu 14.04 includes ruby 1.9.3, so setting GEM_HOME and installing that way doesn't work
