### ISSUE TITLE
CA cert not honored in ldap_entry

### ISSUE THREAD

**Issue by disconn3ct** [datacentred/datacentred-ldap#75]
When setting up the server, the CA cert can be defined and it configures ldap.conf accordingly, but it is not honored by ldap_entry. (The only workaround is to set `self_signed => true`, which has security implications.)

According to http://www.rubydoc.info/gems/net-ldap/Net/LDAP the CA certificate could be passed in with `tls_options => { :ca_file => "/etc/cafile.pem" }`

**Comment by seanhandley** [comment]
Thanks for raising the issue @disconn3ct.

We don't get much time to maintain this at the moment so if you're able to submit a pull request we'd be grateful!
