### ISSUE TITLE
Can't connect to the server - SSL config issue?

### ISSUE THREAD

**Issue by seefood** [datacentred/datacentred-ldap#76]
this is the puppet agent in debug mode. the server is there, the port is bound and listening, the certificates and keys are fine (the syslog shows no complaints), so, where do I start debugging this? (and yes, I know this is very probably an openldap issue and not the puppet module, but I'm hoping somebody bumped into this by now)

```
Debug: Executing: '/bin/systemctl is-active slapd'
Debug: Executing: '/bin/systemctl is-enabled slapd'
Debug: Connecting to LDAP server ldaps://localhost:389
Error: /Stage[main]/Ob_ldap::Ldap_server/Ldap_entry[dc=dev-ira,dc=own-backup,dc=com]: Could not evaluate: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
```

this is on the latest CentOS 7.2.

**Comment by seanhandley** [comment]
Sorry @seefood - we don't get much time to maintain this module (though pull requests are welcome if you find/fix a bug in the Puppet code itself!)

I'm closing this issue - feel free to re-open if you have more to add.
